<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <SupportedOSPlatformVersion>7.0</SupportedOSPlatformVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="AntdUI\**" />
    <Compile Remove="bin\**" />
    <EmbeddedResource Remove="AntdUI\**" />
    <EmbeddedResource Remove="bin\**" />
    <None Remove="AntdUI\**" />
    <None Remove="bin\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove=".editorconfig" />
    <None Remove=".filenesting.json" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="bin\Debug\net8.0-windows7.0\DH_Control_Demo.deps.json" />
    <Content Include="bin\Debug\net8.0-windows7.0\DH_Control_Demo.runtimeconfig.json" />
    <Content Include="bin\Debug\net8.0-windows7.0\Gecat.xml" />
    <Content Include="bin\Debug\net8.0-windows7.0\Image\MCE.png" />
    <Content Include="bin\Debug\net8.0-windows7.0\Image\RGI-100-30.png" />
    <Content Include="bin\Debug\net8.0-windows7.0\Image\SoftLand.png" />
    <Content Include="bin\Debug\net8.0-windows7.0\Image\VLA.png" />
    <Content Include="bin\Debug\net8.0-windows7.0\Image\微信截图_20231013102838.png" />
    <Content Include="bin\Debug\net8.0-windows7.0\Image\微信截图_20250311171321.png" />
  </ItemGroup>

  <ItemGroup>
    <None Include="bin\Debug\net8.0-windows7.0\AngusTools.dll" />
    <None Include="bin\Debug\net8.0-windows7.0\AntdUI.dll" />
    <None Include="bin\Debug\net8.0-windows7.0\Config\AxisConfig.config" />
    <None Include="bin\Debug\net8.0-windows7.0\DH_Control_Demo.dll" />
    <None Include="bin\Debug\net8.0-windows7.0\DH_Control_Demo.exe" />
    <None Include="bin\Debug\net8.0-windows7.0\DH_Control_Demo.pdb" />
    <None Include="bin\Debug\net8.0-windows7.0\Image\新建 Microsoft Word 文档.docx" />
    <None Include="bin\Debug\net8.0-windows7.0\Log\2026-05-24 - 副本.log" />
    <None Include="bin\Debug\net8.0-windows7.0\Log\2026-05-24.log" />
    <None Include="bin\Debug\net8.0-windows7.0\Log\2026-05-25.log" />
    <None Include="bin\Debug\net8.0-windows7.0\LTDMC.dll" />
    <None Include="bin\Debug\net8.0-windows7.0\LTDMC.lib" />
    <None Include="bin\Debug\net8.0-windows7.0\runtimes\win\lib\net8.0\System.Text.Encoding.CodePages.dll" />
    <None Include="bin\Debug\net8.0-windows7.0\System.Text.Encoding.CodePages.dll" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="AngusTools">
      <HintPath>Libs\AngusTools.dll</HintPath>
    </Reference>
    <Reference Include="AntdUI">
      <HintPath>bin\Debug\net6.0-windows\AntdUI.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <EditorConfigFiles Remove="D:\Angus\A03成果\标准化工作\运动控制卡\DH_Control_Demo\.editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <EditorConfigFiles Remove="D:\Angus\A03成果\标准化工作\运动控制卡\DH_Control_Demo\.editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <EditorConfigFiles Remove="D:\Angus\A03成果\标准化工作\运动控制卡\DH_Control_Demo\.editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Text.Encoding.CodePages" Version="9.0.3" />
  </ItemGroup>

</Project>